apiVersion: v1
data:
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.umbl.com/realms/argo
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    extraParams: |
      prompt=login
      max_age=0
  url: https://argocd.umbl.com
  # Creating users , apikey > will generate token
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2024-09-21T05:16:44Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "474478"
  uid: f85000f0-de25-4255-9531-b2518ca732a3
data:
  policy.csv: |
    g, argocd-admin, role:admin
    g, argocd-developer, role:developer
    p, role:admin, applications, *, allow
    p, role:developer, applications, get, allow
